name: Build and deploy

on:
    push:
        branches: [master]

# Fixes the deprecation warnings by forcing the runner to use Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: write

        steps:
            # UPDATED: Use v4 to support Node 24
            - uses: actions/checkout@v4

            - name: Prepare environment
              # UPDATED: Use v4 to support Node 24
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # You can keep your code at 20, but the runner needs v4

            - run: npm install --global pnpm

            - name: Install deps
              run: pnpm m i

            - name: Build plugin(s)
              run: node ./build.mjs

            - name: Copy additional files
              run: |
                  cp README.md dist/README.md
                  printf -- "---\npermalink: /404.html\n---\n" > dist/404.md
                  printf -- "> **Note:** You accessed a link that returned a 404, probably by clicking one of the plugin links. You're supposed to copy the link address and add it into Vendetta.\n\n" >> dist/404.md
                  cat README.md >> dist/404.md

            - name: Deploy to GitHub Pages
              # UPDATED: Use v4 to resolve Node 20 deprecation warnings
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  enable_jekyll: true
